---

-  hosts: all
   become: true
   tasks:

   - name: Update the system packages
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     changed_when: false

   -  name: install more than one packages for ubuntu
      tags: ubuntu,nmap.apache,ufw
      apt:
        name:
           - nmap
           - apache2
           - ufw
        state: latest
      when: ansible_distribution == "Ubuntu"

   - name: copy default html file for site
     tags: apache
     copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644


   -  name: install vlc
      tags: vlc
      community.general.snap:
        name: vlc
        state: latest
      when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: workstation
  become: true
  tasks:
  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


- hosts: Web_Server
  become: true
  tasks:
  - name: install the file sharing package
    tags: web_server
    package:
      name: samba
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache2
    apt:
      name:
        - apache2

      state: latest 
#This starts and enable the service
  - name: start apache service
    tags: apache
    service:
      name: apache2
      state: started
      enabled: yes 
    when: ansible_distribution == "Ubuntu"      
