---

-  hosts: all
   become: true
   tasks:

   - name: Update the system packages
     tags: always
     apt:
       upgrade: dist
      #update_cache: yes
     changed_when: false

#This Lines Define how to insert roles
- hosts: Web_Server
  become: true
  roles:
    - Web_Server

- hosts: workstation
  become: true
  roles:
    - workstation

- hosts: all
  become: true
  roles:
    - base
