---

- hosts: all
  become: true
  tasks:
  - name: copy default_site html file
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
